replicaCount: 1
namespace: kubeflix

image:
  repository: movie-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5002

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: ENVIRONMENT
    value: production

containerPort: 5002

probes:
  livenessProbe:
    httpGet:
      path: /health
      port: 5002
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    httpGet:
      path: /health
      port: 5002
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
