apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: kubeflix
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  type: NodePort

